services:
  db:
    image: postgres:15
    container_name: pathfinding_db
    restart: always
    environment:
      # Questi valori servono solo all'avvio del container DB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crowd_pathfinding
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pathfinding_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db